runtime: python27
api_version: 1
threadsafe: true
handlers:

- url: /(.*\.(gif|png|jpg|css|js)(|\.map))$
  static_files: dist/\1
  upload: dist/(.*)(|\.map)

- url: /(.*)
  static_files: dist/index.html
  upload: dist/index.html

- url: /assets
  static_dir: static/assets
  http_headers:
    Access-Control-Allow-Origin: https://birdman-app-bucket.appspot.com